//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freebox.BootstrapperApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freebox.BootstrapperApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action abandonnée..
        /// </summary>
        public static string strActionCanceled {
            get {
                return ResourceManager.GetString("strActionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter l&apos;installation.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string strCancelButton {
            get {
                return ResourceManager.GetString("strCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandon en cours ....
        /// </summary>
        public static string strCanceling {
            get {
                return ResourceManager.GetString("strCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string strCancelNo {
            get {
                return ResourceManager.GetString("strCancelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etes vous sûr de quitter ?.
        /// </summary>
        public static string strCancelText {
            get {
                return ResourceManager.GetString("strCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string strCancelYes {
            get {
                return ResourceManager.GetString("strCancelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        public static string strFinishButton {
            get {
                return ResourceManager.GetString("strFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;état d&apos;installation  est inconnu..
        /// </summary>
        public static string strInstallationStateUnknown {
            get {
                return ResourceManager.GetString("strInstallationStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installer.
        /// </summary>
        public static string strInstallButton {
            get {
                return ResourceManager.GetString("strInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;installation est terminée..
        /// </summary>
        public static string strInstallComplete {
            get {
                return ResourceManager.GetString("strInstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoire d&apos;installation.
        /// </summary>
        public static string strInstallDir {
            get {
                return ResourceManager.GetString("strInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installation en cours ....
        /// </summary>
        public static string strInstalling {
            get {
                return ResourceManager.GetString("strInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de prendre connaissance des termes de la licence avant de 
        ///procéder à l&apos;installation de cette application..
        /// </summary>
        public static string strInstallLicenseTerms {
            get {
                return ResourceManager.GetString("strInstallLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;un autre répertoire.
        /// </summary>
        public static string strInstallSelection {
            get {
                return ResourceManager.GetString("strInstallSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir installé {0}!.
        /// </summary>
        public static string strInstallThankyou {
            get {
                return ResourceManager.GetString("strInstallThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration de votre système.
        /// </summary>
        public static string strMessageInitialize {
            get {
                return ResourceManager.GetString("strMessageInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string strNextButton {
            get {
                return ResourceManager.GetString("strNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez patienter durant la desinstallation de {0} 
        ///sur votre ordinateur. 
        ///Cela peut prendre plusieurs minutes ....
        /// </summary>
        public static string strPleaseWaitWhileCanceling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez patienter durant l&apos;installation de {0} 
        ///sur votre ordinateur. 
        ///Cela peut prendre plusieurs minutes ....
        /// </summary>
        public static string strPleaseWaitWhileInstalling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez patienter durant la maintenace de {0}
        /// sur votre ordinateur. 
        ///Cela peut prendre plusieurs minutes ....
        /// </summary>
        public static string strPleaseWaitWhileRepairing {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez patienter durant la desinstallation de {0}
        /// sur votre ordinateur. 
        ///Cela peut prendre plusieurs minutes ....
        /// </summary>
        public static string strPleaseWaitWhileUninstalling {
            get {
                return ResourceManager.GetString("strPleaseWaitWhileUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réparer.
        /// </summary>
        public static string strRepairButton {
            get {
                return ResourceManager.GetString("strRepairButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La maintenance est terminée..
        /// </summary>
        public static string strRepairComplete {
            get {
                return ResourceManager.GetString("strRepairComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maintenance en cours ....
        /// </summary>
        public static string strRepairing {
            get {
                return ResourceManager.GetString("strRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir choisi {0}!.
        /// </summary>
        public static string strRepairThankyou {
            get {
                return ResourceManager.GetString("strRepairThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désinstaller.
        /// </summary>
        public static string strUninstallButton {
            get {
                return ResourceManager.GetString("strUninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désinstallation terminée..
        /// </summary>
        public static string strUninstallComplete {
            get {
                return ResourceManager.GetString("strUninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désinstallation en cours ....
        /// </summary>
        public static string strUninstalling {
            get {
                return ResourceManager.GetString("strUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir choisi{0}!.
        /// </summary>
        public static string strUninstallThankyou {
            get {
                return ResourceManager.GetString("strUninstallThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations avant installation :.
        /// </summary>
        public static string strWelcometext {
            get {
                return ResourceManager.GetString("strWelcometext", resourceCulture);
            }
        }
    }
}
